# tolerance 1-10
tolerance: 4

# true or false
hasVideo: false

window:
  width: 800
  height: 600

#
userMap:
  example:
    keyMap:
  #    - "CMD a"
  #    - "cmd m"
    funcMap:
      - "pycharm"
      - "idea"
